### ISSUE TITLE
Name/Rename of attribute usageZoneClass

### ISSUE THREAD

**Issue by gioagu** [cstb/citygml-energy#75]
Some comments/thought collected so far to be considered for version 0.7

Giorgio: I would rename the attribute “usageZoneClass” to “usageZoneType”. We are defining the type of usage zone. We should stay coherent to BuildingType, OccupantsType, atticType, etc.

Joachim: I am not sure about this. usageZoneClass uses the general CityGML Codelist BuildingClass, and this Codelist is used by the attribute  class in the CityGML feature _AbstractBuilding. Thus, the actual naming is consistent with CityGML. However, I am not sure whether BuildingClass is really a good choice for the classification of UsageZones. In CityGML, a building may have an unique “classification of it’s actual usage”, which is expressed by the class attribute. Therefore, different UsageZones formally cannot have different usageZoneClass values. 
I propose to leave this problem for ADE version 0.7.

**Comment by JoachimBenner** [comment]
Rename: usageZoneClass --> usageZoneType. Agree on a new CodeList, or use an existing one.

**Comment by lucagiovannini** [comment]
I think the best would be to use INSPIRE codelist CurrentUseValue:

- Example of INSPIRE base (mandatory): http://inspire.ec.europa.eu/codelist/CurrentUseValue
- Example of the same INSPIRE codelist extended with new values: http://hub.geosmartcity.eu/registry/codelist/CurrentUseValue/
- Another example of codelist of CurrentUse extending INSPIRE: http://www.locationframework.eu/codelist/CurrentUseValue.html

**Comment by RomainNouvel** [comment]
Thanks for the inputs Luca.
Just to remind you the codeList "BuidingClassType" of CityGML:
![buildingclasstype](https://cloud.githubusercontent.com/assets/11771239/14886545/9f57da7e-0d51-11e6-88ff-d4e001b88bf1.png)
In my mind, it covers also well our need...

**Comment by RomainNouvel** [comment]
The INSPIRE base codelists includes 4 different Usages for "residential" depending on the BuildingType...  usage should be actually independant from the building type and form, isn't it? The two other codelist seems ok...

**Comment by JoachimBenner** [comment]
I think, we need to make some general decisions concerning specification and usage of CodeLists in the ADE:

1. What is the role of the "Base Codelist"? In INSPIRE, the values of the Base Codelist can be used anyway, but some CodeLists are "extensible". I think, we should use the same principle, but our CodeLists are always extensible. Do you agree?

2. Which Base Codelists do we use? Especially in this case, shall we use the CityGML version of "BuildingClass", the CityGML version of "Building Usage", or the INSPIRE Codelist for "CurrentUse", with or without some extension? I personally have the feeling that the Base Codelist should not be too complex and detailled, but on the other hand this could imply that always an extension must be used, which affects the interoperability. What do you mean?

3. How do we specify CodeLists in the UML diagram? In INSPIRE, the entries of the Base CodeList are specified in the diagram as notes, and the URL of the Base Codelist is specified as Tagged Value "vacabulary". I propose to use the same style in the Energy ADE.

**Comment by lucagiovannini** [comment]
I agree with Joachim:

1. I think that specifying a URL to some official codelist listing is fundamental for clarity.

3. I think we should adopt a base codelist and I strongly support that we choose INSPIRE CurrentUse for the sake of interoperability.

This below is the tree of the mandatory values of INSPIRE CurrentUse.
I agree that the second level of residential is some kind of a mixture with BuildingType, but I believe that conforming to an official standard still remains more important.
I propose that we choose as "base codelist" the INSPIRE CurrentUse up to the second level (and excluding the third), so that the choice of office/trade/publicServices as keywords is fixed officially (if we don't do this, everyone will make a different choice of keywords: trade, shops, retail, commerce, etc)

```
residential		
	individualResidence	
	collectiveResidence	
		twoDwellings
		moreThanTwoDwellings
	residenceFor Communities	
agriculture		
industrial		
commerceAndServices		
	office	
	trade	
	publicServices	
ancillary	
```

**Comment by RomainNouvel** [comment]
Request of Change:
- In UsageZone, rename attribute “usageZoneClass” to “usageZoneType" (Type: CodeList)
- The CodeList source is:  http://hub.geosmartcity.eu/registry/codelist/CurrentUseValue/

**Comment by JoachimBenner** [comment]
Theoretically, this looks easy, but as a software developer I still have a lot of questions how to implement the concept:
- Within one part of the registry like , e.g.  http://hub.geosmartcity.eu/registry/codelist/CurrentUseValue/, there are lots of different representations of the same CodeList, differing by the used language and the Codelist encoding style (2 different XML versions, RDF, JSON; ...). Which of these representation shall be used, or can we leave this decision to the user?
- In the XML encoding of the Energy ADE, a CodeList attribute is modelled as *gml:CodeType*. This means that in the instance document two pieces of information must be given:
 - The *codeSpace*, which is an URL pointing to the used CodeList, and
 - The *code* itself.

Is this example for specifying the usageZoneType "commerce and services", based on the INSPIRE CodeList for CurrentUse, correct:

![encoding](https://cloud.githubusercontent.com/assets/6430204/15173278/7ea35db2-175b-11e6-9901-8941ce0cca81.png)

**Comment by lucagiovannini** [comment]
Dear All,

shouldn't the example above be like this?
`<usageZoneType codeSpace="http://hub.geosmartcity.eu/registry/codelist/CurrentUseValue/">
     commerceAndServices
</usageZoneType>
`

In my opinion the codeSpace is an URL pointing to the full list of the codelist values (that anyone can consult, in any language and format for the sole purpose of learning the possible values), while the code itself it's not a URL but just the English label for the type of usageZone.

**Comment by JoachimBenner** [comment]
Dear colleagues,

I would appreciate to specify the usage of INSPIRE CodeLists in the Energy ADE in this way, but it must be clear that this is not exactly the “INSPIRE way”.

If you look e.g. into one of the XML encodings  of the CurrentUse CodeList, you will only find the complete URL (http://hub.geosmartcity.eu/registry/codelist/CurrentUseValue/commerceAndServices) as Id of a specific CodeList entry. The point is, that the INSPIRE schemata use a different encoding for CodeList  attributes than CityGML and the CityGML Energy ADE: INSPIRE uses gml:ReferenceType, and CityGML uses gml:CodeType. For the INSPIRE encoding, only the complete URL is needed, while the gml:CodeType (see the example of Giovanni) cuts the information into two pieces: The codeSpace (an URL pointing to the complete CodeList) and the code itself, specified as textual content of the XML element. Thus, for generating the Id of a specific CodeList item, codeSpace and code must be concatenated.

Can we agree to use all Energy ADE CodeLists in this way, and to explain it in the guidelines?

Best regards

Joachim
_________________________________________________________
Dr. Joachim Benner
Karlsruher Institut für Technologie (KIT)
Institut für Angewandte Informatik
Herrmann-von-Helmholtz-Platz 1
Bau 445, Raum 337
76344 Eggenstein-Leopoldshafen

Tel.:       +49 (0)721 608 22534
Fax:       +49 (0)721 608 25786
E-Mail:  joachim.benner@kit.edu<mailto:joachim.benner@kit.edu>

**Comment by lucagiovannini** [comment]
Dear Joachim, Dear All,

I discussed the issue also with my colleague Piergiorgio and we confirm our support for such a solution, with the adjustment that the codeSpace attribute should contain the URL to a machine-readable description of the codelist (the XML file "CurrentUseValue.de.xml" in the example below). 
We also think that no constraints are needed on encoding (XML, RDF, JSON) or language because that information can be machine-derived form the codelist file itself.

```
<usageZoneType codeSpace="http://hub.geosmartcity.eu/registry/codelist/CurrentUseValue/CurrentUseValue.de.xml"> commerceAndServices
</usageZoneType>
```

Best regards,

Luca

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
